Update codeql.yml

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -9,24 +9,8 @@ on:
     branches: [ "master" ]
   schedule:
     - cron: 00 23 * * *
-jobs:
-  Checkov:
-      runs-on: ubuntu-latest
-      steps:
-       - uses: actions/checkout@v4
-       - name: Set up Python 3.8
-         uses: actions/setup-python@v4
-         with:
-           python-version: 3.8
-       - name: Test with Checkov
-         id: checkov
-         uses: bridgecrewio/checkov-action@master
-         with:
-          directory: example/examplea
-          framework: terraform 
-          
+jobs:          
   Linter:  # Причесываем код для проверок 
-     needs: Checkov
      name: Lint
      runs-on: ubuntu-latest
 
@@ -50,46 +34,46 @@ jobs:
                 DEFAULT_BRANCH: "master"
                 # To report GitHub Actions status checks
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-            continue-on-error: true
+            continue-on-error: true # не прерываем на ошибке. 
 
-  analyze:
-    needs: Linter
-    name: Analyze (${{ matrix.language }})
-    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
-    permissions:
-      security-events: write
-      packages: read
-      actions: read
-      contents: read
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-        - language: javascript-typescript
-          build-mode: none
-        - language: python
-          build-mode: none
-    steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
-    - name: Initialize CodeQL
-      uses: github/codeql-action/init@v3
-      with:
-        languages: ${{ matrix.language }}
-        build-mode: ${{ matrix.build-mode }}
-    - if: matrix.build-mode == 'manual'
-      shell: bash
-      run: |
-        echo 'If you are using a "manual" build mode for one or more of the' \
-          'languages you are analyzing, replace this with the commands to build' \
-          'your code, for example:'
-        echo '  make bootstrap'
-        echo '  make release'
-        exit 1
-    - name: Perform CodeQL Analysis
-      uses: github/codeql-action/analyze@v3
-      with:
-        category: "/language:${{matrix.language}}"
+#  analyze:
+#    needs: Linter
+#    name: Analyze (${{ matrix.language }})
+#    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
+#    permissions:
+#      security-events: write
+#      packages: read
+#      actions: read
+#      contents: read
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        include:
+#        - language: javascript-typescript
+#          build-mode: none
+#        - language: python
+#          build-mode: none
+#    steps:
+#    - name: Checkout repository
+#      uses: actions/checkout@v4
+#    - name: Initialize CodeQL
+#      uses: github/codeql-action/init@v3
+#      with:
+#        languages: ${{ matrix.language }}
+#        build-mode: ${{ matrix.build-mode }}
+#    - if: matrix.build-mode == 'manual'
+#      shell: bash
+#      run: |
+#        echo 'If you are using a "manual" build mode for one or more of the' \
+#          'languages you are analyzing, replace this with the commands to build' \
+#          'your code, for example:'
+#        echo '  make bootstrap'
+#        echo '  make release'
+#        exit 1
+#    - name: Perform CodeQL Analysis
+#      uses: github/codeql-action/analyze@v3
+#      with:
+#        category: "/language:${{matrix.language}}"
         
 ###
 #Проверка на наличие утечек 
